zha:
  custom_quirks_path: /config/zha_quirks/
  zigpy_config:
    # https://www.home-assistant.io/integrations/zha#ota-firmware-updates
    ota:
      ikea_provider: true # Auto update Trådfri devices
      sonoff_provider: true # Auto update Sonoff devices

# https://github.com/mdeweerd/zha-toolkit
zha_toolkit:
